### ISSUE TITLE
Error: Could not find access token

### ISSUE THREAD

**Issue by neeraj87** [hunkim/Wit-Facebook#16]
When I run the app it gives the "could not find access token error"

```
Error: Could not find access token, learn more at https://wit.ai/docs
    at validate (/Volumes/Macintosh HD 2/GitHub Cloned Repos/node-wit.ai/node_modules/node-wit/lib/wit.js:210:11)
    at new Wit (/Volumes/Macintosh HD 2/GitHub Cloned Repos/node-wit.ai/node_modules/node-wit/lib/wit.js:24:45)
    at Object.getWit (/Volumes/Macintosh HD 2/GitHub Cloned Repos/node-wit.ai/bot.js:82:10)
    at Object.<anonymous> (/Volumes/Macintosh HD 2/GitHub Cloned Repos/node-wit.ai/app.js:13:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
```
As far as I know my access token is there on the const.js file

**Comment by tarokawada** [comment]
Same issue is happening to me but i saved mine in config variable. Have you found a way to resolve this?

**Comment by timxor** [comment]
+1

**Comment by willian-viana** [comment]
+1

**Comment by hunkim** [comment]
Any solution for this?

**Comment by Rolfjdra** [comment]
I never had this issue until now. I solved it by changing:
"return new Wit(Config.WIT_TOKEN, actions);"
to
"return new Wit({ accessToken: Config.WIT_TOKEN, actions: actions });"

You can give that a try ;)
